### ISSUE TITLE
Set default data color so all boxes are the same color in Box & Whisker chart

### ISSUE THREAD

**Issue by mlongoriabg** [liprec/PowerBI-custom-visuals#13]
I like this visual and am currently using it. But it doesn't seem to have a way to set the default color for all boxes in the Data Colors section. I can set the color for each individual category, but when I refresh my data, the new categories appear with the original color. I should be able to set the default color and have any new boxes appear with that color. There isn't a good reason to have each box be a different color, and it seems to be against data viz guidelines to do so without purpose. The image below is from the built-in bar chart in Power BI. Perhaps this Box and Whisker chart could have this as well.
![image](https://user-images.githubusercontent.com/15305668/27550429-d761aa2c-5a5c-11e7-8779-ed431bc7dba3.png)

Note: I haven't tried to see how using a report theme affects this.

**Comment by liprec** [comment]
Thanks for the feedback. At this moment when there are more than 15 categories (Boxes) then all boxes will be drawn in the same color. There is a bug that the formatting pane is changed only if there are more that 25 categories.
But I will add an option to select that all boxes can be drawn in the same color, regardless of the number of categories..

**Comment by liprec** [comment]
In the new version of my visual there is an option to enable one color for all boxes. In the next 1-2 weeks this version will be available for everyone.

And I have moved the Box and Whisker chart to it's own repository: https://github.com/liprec/powerbi-boxWhiskerChart/
