### ISSUE TITLE
Selection is only OR and not AND as in example

### ISSUE THREAD

**Issue by RuudPolly** [liprec/PowerBI-custom-visuals#14]
I want to use the slicer to select multiple months at once, but I can only select one at a time. In the example, multiple selection is possible.

![image](https://user-images.githubusercontent.com/29734840/27595914-4dc5f130-5b5e-11e7-9304-1d0fdaa94d41.png)

**Comment by liprec** [comment]
By default the slicer acts as 'single select' and in that mode you can only select one month at the time. If you click on the formatting pane (click on the little paint roller next to the field selector) you can alter the behavior and disable the single select to enable multi select.
After that you can select multiple values, like May and June together as selection.

-JP
