### ISSUE TITLE
Add 'Do not summarize' option to the value (Visualization working inPower BI Desktop June 2017?)

### ISSUE THREAD

**Issue by cmeiklejohn** [liprec/PowerBI-custom-visuals#15]
Every time I try to use this visualization, nothing is rendering and the output just states that "Dataset is not valid or too small/empty to display this visualization"

Here's information about my version of Power BI:
Version: 2.47.4766.801 64-bit (June 2017)

My data set is a simple single column of numbers and I'm just trying to render a single box and whisker plot with this before moving on to my more complicated data set.

**Comment by cmeiklejohn** [comment]
So, I think I found the problem here.  On my numeric field, there isn't an option to "Do not summarize" so it's summing up the table of values into a single table.  Is there a reason that the "Do not summarize" option is not available?

**Comment by liprec** [comment]
The reason behind it, is that the Box and Whisker chart calculates the values itself and therefor it needs the 'raw' data records. So the values shouldn't be 'pre-summarized' before the boxes are calculated and drawn.

**Comment by cmeiklejohn** [comment]
But, I think the issue here is that my data is pre summarized and there is
no option to not summarize the column.

**Comment by liprec** [comment]
Sorry, I misunderstood and must say that there is no specific reason why the "Do not summarize" is missing. Let me dig into this and look how and if I can add this one as it can add value to the visual.

**Comment by liprec** [comment]
I have updated my visual (and moved to a new repository https://github.com/liprec/powerbi-boxWhiskerChart), but it looks like I cannot enable the 'Do not summarize' option and combine it with the datarole I am using.
I am adding support for drill down in a next version (https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Drilldown.md) and therefor I cannot change the dateRole mapping, so I have to close this issue as it is not possible to achieve.

Alternative you can add a 'rowId' column and used it to sample the dataset for my visual.
