### ISSUE TITLE
Hierarchy Slicer - Search only available when header displayed issue

### ISSUE THREAD

**Issue by dshadfield** [liprec/PowerBI-custom-visuals#17]
The Power BI Hierarchy Slicer will only allow the Search to be enabled when the header is displayed. Can this be resolved so that the search can be enabled without header being displayed?
@liprec

**Comment by liprec** [comment]
I will solve this issue in the next release.
Thanks for the feedback.

**Comment by liprec** [comment]
Fixed in v1.1.5
