### ISSUE TITLE
Support Ragged Hierachies (Hierarchy slicer, power bi)

### ISSUE THREAD

**Issue by gitonup23** [liprec/PowerBI-custom-visuals#3]
Hi Jan,

I'm using your hierarchy slicer, find it very useful, really nice add on to the standard visualizations. Have a problem with blanks in the hierarchy, I see you have it in your dev pipeline - do you have an ETA for the next release?

Thanks and regards

Ger

**Comment by liprec** [comment]
Hi,

Thanks for the feedback and in the next major release this item will be included.

-JP

**Comment by liprec** [comment]
In the next 1-2 weeks a new version of the HierarchySlicer will be available for everybody and that version has support for ragged hierarchies.
