### ISSUE TITLE
DropDown option (HierarchySlicer Update)

### ISSUE THREAD

**Issue by timhettinger** [liprec/PowerBI-custom-visuals#9]
Hi,

Is it possible to make the HierarchySlicer a dropdown similar to the dropdown capability of the Slicer developed by Microsoft already built into Power BI?  I have not been able to find a way to do this and it would be helpful to have a dropdown box where you could then view the full tree slicer.  Happy to communicate through email to discuss.

Thanks,
A user

**Comment by liprec** [comment]
Hi,

I have put the dropdown request on the backlog for a future version.

Thanks, Jan Pieter

**Comment by liprec** [comment]
Added in v1.1.5

**Comment by timhettinger** [comment]
Awesome! Thank you! I will check it out

**Comment by robrien6** [comment]
Hi,

I cant find this enhancement in V1.1.5 - is is definitely in there?

**Comment by liprec** [comment]
Your right. Somehow I mixed up this enhancement with another one.
To conclude: this is not added to the visual and also will not be available any time soon, due to API limitations.

**Comment by liprec** [comment]
Added to the current issue list: [#21](https://github.com/liprec/powerbi-hierarchySlicer/issues/21)

**Comment by RobertSkoglund** [comment]
Any updates to this request?
